name: Create and publish a Docker image

on:
  workflow_dispatch:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  deploy-to-container-app:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WEBMAJIANG202503170914CA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEBMAJIANG202503170914CA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEBMAJIANG202503170914CA_AZURE_SUBSCRIPTION_ID }}

      # パブリックGHCRイメージをContainer Appにデプロイ
      - name: Deploy public GHCR image to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: webmajiang-202503170914-ca
          resourceGroup: webmajiang-202503170914-rg
          imageToDeploy: ghcr.io/dahlia1209/webmajiang-server:${{ github.sha }}
          registryServer: ghcr.io
