name: Trigger auto deployment for webmajiang-202503170914-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/webmajiang-202503170914-ca-AutoDeployTrigger-40abd56a-31d5-4cf6-9095-19495d7e8710.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WEBMAJIANG202503170914CA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEBMAJIANG202503170914CA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEBMAJIANG202503170914CA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.WEBMAJIANG202503170914CA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBMAJIANG202503170914CA_REGISTRY_PASSWORD }}
          containerAppName: webmajiang-202503170914-ca
          resourceGroup: webmajiang-202503170914-rg
          imageToBuild: ghcr.io/webmajiang-202503170914-ca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


